[project]
name = "sablenda"
version = "0.1.0"
description = "An accessible agenda"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "wxpython>=4.2.4",
]

[dependency-groups]
dev = [
    "nuitka>=2.8.4",
]
